application: gdrinkr
version: xxversioncodexx
runtime: python27
threadsafe: yes
api_version: 1

libraries:
- name: webapp2
  version: "latest"
- name: django
  version: "latest" #version: "1.3"
- name: jinja2
  version: latest

default_expiration: "30m"

handlers:
# - url: /google75906d613a2a09ba.html
#   static_files: static/google75906d613a2a09ba.html
#   upload: static/google75906d613a2a09ba.html

- url: /(.+\.(appcache|manifest))
  expiration: "0s"
  mime_type: text/cache-manifest
  static_files: \1
  upload: (.*\.(appcache|manifest))

- url: /favicon.ico
  static_files: web-assets/favicon.ico
  upload: web-assets/favicon.ico

- url: /languages/(.+\.json)
  expiration: "0s"
  mime_type: application/json
  static_files: languages/\1
  upload: /languages/(.*\.json)

- url: /img
  static_dir: img

- url: /scripts
  static_dir: scripts

- url: /(.+\.woff)
  mime_type: application/x-font-woff
  static_files: \1
  upload: (.*\.woff)

- url: /styles
  static_dir: styles

- url: /web-assets
  static_dir: web-assets

- url: /
  static_files: index.html
  upload: index.html

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /drinkr.html
  static_files: drinkr.html
  upload: drinkr.html

- url: /.*
  script: main.app
